
- name: Install Isync/Mbsync
  package:
    name: isync
    state: present

- name: Fetch web.de login
  shell: pass personal/web.de | awk '/email/ {print $2}'
  register: WEBDE_USER

- name: Fetch yahoo login
  shell: pass personal/yahoo.com | awk '/email/ {print $2}'
  register: YAHOO_USER

- name: Fetch outlook login
  shell: pass personal/outlook.de | awk '/email/ {print $2}'
  register: OUTLOOK_USER

- name: Fetch th login
  shell: pass personal/thm | awk '/email/ {print $2}'
  register: TH_USER

- name: Create config from template
  #  vars:
  #    - WEBDE_USER: WEBDE_USER.stdout
  #    - YAHOO_USER: YAHOO_USER.stdout
  #    - OUTLOOK_USER: OUTLOOK_USER.stdout
  #    - TH_USER: TH_USER.stdout
  template:
    src: mbsyncrc.j2
    dest: "{{role_path}}/files/mbsyncrc"

- name: Link isync config
  file:
    src: "{{role_path}}/files"
    dest: "{{config_dir}}/isync"
    state: link
