#!/bin/sh

userresources=$XDG_CONFIG_HOME/x11/Xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

#if [ -d /etc/X11/xinit/xinitrc.d ] ; then
# for f in /etc/X11/xinit/xinitrc.d/* ; do
#  [ -x "$f" ] && . "$f"
# done
# unset f
#fi

sh $XDG_CONFIG_HOME/feh/feh-bg.sh

setxkbmap -model pc105 -layout de -variant nodeadkeys 

xbindkeys -f $XDG_CONFIG_HOME/xbindkeys/xbindkeysrc

exec i3
